### ISSUE TITLE
Details on the different sessions

### ISSUE THREAD

**Issue by saisubramaniam147** [xyutao/bocl#1]
Please provide details on how the Cifar10/100 datasets were split into different sessions, and the code to replicate the illumination and saturation transformations.

**Comment by xyutao** [comment]
The details are now contained in data/datasets.py

For CIFAR10, we just use the 5 binary files  "data_batch_1.bin" ~ "data_batch_5.bin" of the original training sets as the 5 sessions;
For CIFAR100, we shuffle the 50000 training images (with a fixed seed) and then split them into 5 sessions.

The illumination and saturation transformations are implemented as

`def brightness_aug(data, brightness):`
&ensp; `return data * (1 + brightness)`

`def saturation_aug(data, saturation):`
&ensp;`coef = np.array([[[[0.299, 0.587, 0.114]]]])`
&ensp;`gray = data * coef`
&ensp;`gray = np.sum(gray, axis=3, keepdims=True)`
&ensp;`gray *= saturation`
&ensp;`return gray * saturation + data * (1 + saturation)`

Usage:
https://github.com/xyutao/bocl/blob/a01808ad0d36630eddca1c9849296a6b1b079489/data/datasets.py#L50

**Comment by saisubramaniam147** [comment]
Thanks for the prompt update!

Another query - 

>  For fair comparison, we implement all methods using the same network(ResNet18) and measure each method under the same size of the memory that stores pillars or image exemplars.

Please provide the # of samples used for image exemplars that have equivalent memory capacity of the SOM size you have mentioned.
> We use SOMs of sizes 15×15, 32×32, 25×25, and64×64for CIFAR10/100, CORe50 and subImageNet, respectively.


Thanks again.

**Comment by xyutao** [comment]
For Figure 3, the number of exemplars in our comparison experiments is:

> CIFAR10: 225 exemplars

> CIFAR100:1024 exemplars

> CORe50: 625 exemplars

For CORe50, we found a SOM of size 15x15 is enough for our method. But for other methods, more exemplars (i.e., 625) are required to achieve comparable performances.

> SubImageNet: 10000 exemplars, i.e.,10 exemplars for each class.

For SubImageNet, we also need more exemplars (i.e., 10000)  for other comparison methods to achieve a comparable performance with a 64x64 SOM.
